### PR TITLE
Some Improvements

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ezraripps** [comment]
If u care could u update this to change new bot.js

**Comment by ezraripps** [comment]
In this is already added

**Comment by ezraripps** [comment]
Um**

**Comment by ghost** [comment]
yup

**Comment by ezraripps** [comment]
Closed cuz no point

**Comment by ghost** [comment]
I refactored your code because it was a big mess. Added proper error handling in the offer section. And added escrow check. Not sure why it is no point ...

**Comment by ezraripps** [comment]
those edits were already made

**Comment by ezraripps** [comment]
Check the code

**Comment by ghost** [comment]
Where is the escrow check? Using a separate function for * accepting * offers is useless, you should have just included it in your statements.

**Comment by ezraripps** [comment]
No cuz I accept twice and there is no point in writing 5 lines twice.

**Comment by ezraripps** [comment]
Line 65 for escrow check

**Comment by ghost** [comment]
"community.startConfirmationChecker(30000, config.identitySecret);" This is line 65, this is not an escrow checker.

**Comment by ezraripps** [comment]
Well what do u mean by escrow check

**Comment by ghost** [comment]
Trade hold, 14 days delay if user doesn't have mobile authenticator.

**Comment by ghost** [comment]
Wiki of tradeoffer-manager: https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer

"escrowDays - How many days the trade will be held if completed due to you (Steam uses the larger value between you and the other user)"

**Comment by ezraripps** [comment]
Oh shit lol

**Comment by ezraripps** [comment]
I'm on phone so cant but if u fix the conflicts I'll merge

**Comment by ghost** [comment]
You can pull it right now, all functions are the same, only the formatting of the require caused the conflicts.

**Comment by ezraripps** [comment]
I'll just fix it once I get on pc

**Comment by ghost** [comment]
Shame you had to lose your verified status this way.

**Comment by ezraripps** [comment]
Lol i mean whatever . Don't think it's bad closing a pull request where the changes have already been made

**Comment by ghost** [comment]
A PR that was made before yours. You didn't have a clue about what escrow was before I made this PR. And now you close mine to integrate it with your own PR. It is rather childish.

**Comment by ezraripps** [comment]
No, i knew what escrow was i just forgot

**Pull request closed without merging**
