### PR TITLE
Hourly pricing updates

### PR DESCRIPTION
**Pull request by ConnorMcF**
#14 
Twice a minute is far too fast for pricing to update

### CODE REVIEW

**Comment by ezraripps** [comment]
Mhm if people want to change they can, not gonna give you the privilege of being a contributor. Read readme first

**Comment by yaneony** [comment]
Then explain which sense it makes to load prices every 30 seconds, even if my API refresh them hourly? You understand that you just increasing the overhead?!

**Comment by ConnorMcF** [comment]
Arze, I don't care about being a contributor. This is obviously made for people who don't know what they're doing, which also means they're going to leave it at 30 seconds, which is just silly. I made this PR so you wouldn't say "I don't have time" etc because all you need to do is merge it.

**Comment by ezraripps** [comment]
Yes ik I'll add today

**Comment by ezraripps** [comment]
Nvm to lazy

**Pull request merged**
